version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /ext/registry
http:
    addr: :5001
    headers:
        X-Content-Type-Options: [nosniff]
    tls:
        certificate: /var/state/apiserver.cert
        key: /var/state/apiserver.key
        clientcas:
            - /var/state/root.cert
health:
   storagedriver:
       enabled: true
       interval: 10s
       threshold: 3
